version: 0.2

env:
  secrets-manager:
    ACCESS_KEY: "AwsPowerShellCredential:AccessKey"
    SECRET_KEY: "AwsPowerShellCredential:SecretKey"

phases:
  install:
    commands:
      - "echo INSTALL PHASE START: `date`"
      - apt-get update -y
      - apt-get install -y wget apt-transport-https software-properties-common
      - wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install -y powershell
      - pwsh -Command "./Setup.ps1"

  pre_build:
    commands:
      - pwsh -Command "Invoke-ScriptAnalyzer -Path . -Settings PSGallery -Recurse -Verbose"

  build:
    commands:
      - pwsh -Command "./Build.ps1"

  post_build:
    commands:
      - pwsh -Command "New-PesterConfiguration -OutVariable PesterConfig"
      - pwsh -Command "$$PesterConfig.TestResult.OutputFormat=NUnitXml"
      - pwsh -Command "$$PesterConfig.TestResult.OutputPath=Tests/Unit.Test.xml"
      - pwsh -Command "$$PesterConfig.TestResult.Enabled=$True"
      - pwsh -Command "Invoke-Pester -Configuration $PesterConfig"

reports:
  Splitwise:
    files:
      - Tests/Unit.Tests.xml
    file-format: NUNITXML

artifacts:
  files:
    - Output/Splitwise/*.ps*1
  name: Splitwise
