version: 0.2

env:
  secrets-manager:
    ACCESS_KEY: "AwsPowerShellCredential:AccessKey"
    SECRET_KEY: "AwsPowerShellCredential:SecretKey"
    MYGET_USER: "MyGet:User"
    MYGET_KEY: "MyGet:Key"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y wget apt-transport-https software-properties-common
      - wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update -y
      - sudo apt-get install powershell nuget -y
      - pwsh -Command "./Setup.ps1"

  pre_build:
    commands:
      - pwsh -Command "Invoke-ScriptAnalyzer -Path . -Settings PSGallery -Recurse -Verbose"

  build:
    commands:
      - pwsh -Command "./Build.ps1"
      - pwsh -Command "./Pester.ps1" 
      - export VERSION=1.0."$CODEBUILD_BUILD_NUMBER"
      - echo $VERSION 
       - nuget sources add -name splitwise -source https://www.myget.org/F/splitwise/api/v2/package -username $MYGET_USER -password $MYGET_KEY -verbosity detailed
       - nuget pack Splitwise.nuspec -version $VERSION
       - nuget push *.nupkg $MYGET_KEY -source https://www.myget.org/F/splitwise/api/v2/package

  post_build:
    commands:
      - ls 
      
reports:
  Splitwise:
    files:
      - Tests/Unit.Test.xml
    file-format: NUNITXML
