version: 0.2

env:
  secrets-manager:
    ACCESS_KEY: "AwsPowerShellCredential:AccessKey"
    SECRET_KEY: "AwsPowerShellCredential:SecretKey"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y wget apt-transport-https software-properties-common
      - wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update -y
      - sudo apt-get install powershell nuget -y
      - pwsh -Command "./Setup.ps1"

  pre_build:
    commands:
      - pwsh -Command "Invoke-ScriptAnalyzer -Path . -Settings PSGallery -Recurse -Verbose"

  build:
    commands:
      - pwsh -Command "./Build.ps1"
      - pwsh -Command "./Pester.ps1"
      - aws codeartifact get-repository-endpoint --domain splitwise --domain-owner 451460415697 --repository Splitwise --format nuget
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain splitwise --domain-owner 451460415697 --query authorizationToken --output text`
      - echo $CODEARTIFACT_AUTH_TOKEN      
      - nuget sources add -name splitwise -Source https://splitwise-451460415697.d.codeartifact.us-east-1.amazonaws.com/nuget/Splitwise/v3/index.json -username aws -password $CODEARTIFACT_AUTH_TOKEN -Verbosity detailed
      - nuget pack Splitwise.nuspec
      - cat ~/.config/NuGet/NuGet.Config
      - nuget
#      - nuget push *.nupkg -Source splitwise

  post_build:
    commands:
      - ls 
      
reports:
  Splitwise:
    files:
      - Tests/Unit.Test.xml
    file-format: NUNITXML
