version: 0.2

env:
  secrets-manager:
    ACCESS_KEY: "arn:aws:secretsmanager:us-east-1:451460415697:secret:AwsPowerShellCredential-aQMkkK:AccessKey"
    SECRET_KEY: "arn:aws:secretsmanager:us-east-1:451460415697:secret:AwsPowerShellCredential-aQMkkK:SecretKey"
    MYGET_USER: "arn:aws:secretsmanager:us-east-1:451460415697:secret:MyGet-CfaaYP:User"
    MYGET_KEY: "arn:aws:secretsmanager:us-east-1:451460415697:secret:MyGet-CfaaYP:Key"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y wget apt-transport-https software-properties-common
      - wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update -y
      - sudo apt-get install powershell nuget -y
      - pwsh -Command "Install-Module AWSPowerShell.NetCore -Force -Verbose"

  pre_build:
    commands:
      - pwsh -Command "Import-Module AWSPowerShell.NetCore -Force -Verbose"
      - export VERSION=1.0."$CODEBUILD_BUILD_NUMBER"
      - pwsh -Command "Use-STSRole -RoleArn 'arn:aws:iam::451460415697:role/Role-SecretManager-ProdAccount-Access' -RoleSessionName 'CodeBuildRoleSession'"
      - pwsh -Command "Set-AWSCredential -AccessKey $Sts.AccessKeyId -Secret $Sts.SecretAccessKey -StoreAs CodeBuildProfile"
#      - pwsh -Command "Invoke-ScriptAnalyzer -Path . -Settings PSGallery -Recurse -Verbose"

  build:
    commands:
      - pwsh -Command "Get-SECSecretValue -SecretId "arn:aws:secretsmanager:us-east-1:451460415697:secret:MyGet-CfaaYP" -AccessKey $Sts.AccessKeyId -SecretAccessKey $Sts.SecretAccessKey -SessionToken $Sts.SessionToken | Select-Object -ExpandProperty SecretString"
#      - pwsh -Command "./Build.ps1"
#      - pwsh -Command "./Pester.ps1" 
#      - nuget pack Splitwise.nuspec -version $VERSION
#      - nuget push *.nupkg $MYGET_KEY -source https://www.myget.org/F/splitwise/api/v2/package

  post_build:
    commands:
      - ls 
      
reports:
  Splitwise:
    files:
      - Tests/Unit.Test.xml
    file-format: NUNITXML

artifacts:
  name: splitwise-$(date +%Y-%m-%d)
  files: "Output/Splitwise/*"
