version: 0.2

env:
  secrets-manager:
    ACCESS_KEY: "AwsPowerShellCredential:AccessKey"
    SECRET_KEY: "AwsPowerShellCredential:SecretKey"

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - export PATH="$PATH:/root/.dotnet/tools"
      - dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
      - dotnet codeartifact-creds install
      - "echo INSTALL PHASE START: `date`"
      - apt-get update -y
      - apt-get install -y wget apt-transport-https software-properties-common
      - wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install -y powershell
      - pwsh -Command "./Setup.ps1"

  pre_build:
    commands:
      - pwsh -Command "dotnet nuget add source $(aws codeartifact get-repository-endpoint --domain splitwise --domain-owner 451460415697 --repository splitwise --format nuget --query repositoryEndpoint --output text)"v3/index.json" -n Splitwise"
      - pwsh -Command "Invoke-ScriptAnalyzer -Path . -Settings PSGallery -Recurse -Verbose"

  build:
    commands:
      - pwsh -Command "./Build.ps1"

  post_build:
    commands:
      - pwsh -Command "./Pester.ps1"

reports:
  Splitwise:
    files:
      - Tests/Unit.Test.xml
    file-format: NUNITXML

artifacts:
  files:
    - Output/Splitwise/*.ps*1
  name: Splitwise
