version: 0.2

env:
  secrets-manager:
    ACCESS_KEY: "AwsPowerShellCredential:AccessKey"
    SECRET_KEY: "AwsPowerShellCredential:SecretKey"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y wget apt-transport-https software-properties-common
      - wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update -y
      - sudo apt-get install powershell nuget unzip -y
      - wget https://a.co/dbGqKq7 -O ~/credprovider.zip
      - ls
      - unzip ~/credprovider.zip
      - ls
      - mkdir -p ~/.nuget/plugins/netfx ~/.nuget/plugins/netcore
      - ls ~/.nuget/plugins
      - cp -R codeartifact-nuget-credentialprovider/netfx/AWS.CodeArtifact.NuGetCredentialProvider ~/.nuget/plugins/netfx
      - cp -R codeartifact-nuget-credentialprovider/netcore/AWS.CodeArtifact.NuGetCredentialProvider ~/.nuget/plugins/netcore
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain splitwise --domain-owner 451460415697 --region us-east-1 --query authorizationToken --output text`
      - pwsh -Command "./Setup.ps1"

  pre_build:
    commands:
      - nuget sources add -name "splitwise/Splitwise" -Source "https://splitwise-451460415697.d.codeartifact.us-east-1.amazonaws.com/nuget/Splitwise/v3/index.json" -Username "aws" -Password "${CODEARTIFACT_AUTH_TOKEN}"
      - pwsh -Command "Invoke-ScriptAnalyzer -Path . -Settings PSGallery -Recurse -Verbose"

  build:
    commands:
      - pwsh -Command "./Build.ps1"
      - pwsh -Command "./Pester.ps1"

  post_build:
    commands:
      - ls
      - nuget pack ./Splitwise.nuspec
      - nuget push Splitwise.0.0.2.nupkg -Source "splitwise/Splitwise"
      
reports:
  Splitwise:
    files:
      - Tests/Unit.Test.xml
    file-format: NUNITXML

artifacts:
  files:
    - Output/Splitwise/*.ps*1
  name: Splitwise
