name: CI Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
  pull_request:
    branches:
      - 'feature/*'
      - 'fix/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        shell: pwsh
        run: Install-Module -Name ModuleBuilder -Verbose -Force

      - name: Build Module
        env:
          PpmBuildVersion: ${{ github.run_number }}
        shell: pwsh
        run: |
          Build-Module -SourcePath Source\Splitwise.psd1 -Version "1.3.$($Env:PpmBuildVersion)"
      
      - name: Publish Module
        shell: pwsh
        run: |
          Get-ChildItem -Path Output/Splitwise
          Publish-Module -Path Output/Splitwise -NugetApiKey ${{ secrets.NuGetApiKey }} -Repository PSGallery -Verbose