name: CI Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
  pull_request:
    branches:
      - 'feature/*'
      - 'fix/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        shell: pwsh
        run: Install-Module -Name ModuleBuilder -Verbose

